#!/usr/bin/env node
/**
 * Syncs data/styles.json with whatever is currently in /resources, then
 * regenerates data/styles.js (the file the browser actually loads).
 *
 *   node scripts/sync.mjs
 *
 * - New image in /resources  -> a draft style entry is appended (category "unsorted")
 * - Image deleted            -> the entry is kept but flagged `missing: true`
 * - Everything you have already written by hand is left untouched.
 */
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, basename, extname } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const RESOURCES = join(ROOT, 'resources');
const JSON_PATH = join(ROOT, 'data', 'styles.json');
const JS_PATH = join(ROOT, 'data', 'styles.js');

const IMAGE_EXT = new Set(['.jpg', '.jpeg', '.png', '.webp', '.gif', '.avif', '.svg']);

const slug = (s) =>
  s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 48) || 'style';

export function sync({ quiet = false } = {}) {
  const db = JSON.parse(readFileSync(JSON_PATH, 'utf8'));
  db.categories ??= [];
  db.styles ??= [];

  if (!db.categories.some((c) => c.id === 'unsorted')) {
    db.categories.push({
      id: 'unsorted',
      name: 'Unsorted (new)',
      accent: '#ff8a3d',
      blurb: 'Images found in /resources that have not been classified yet.',
    });
  }

  const files = existsSync(RESOURCES)
    ? readdirSync(RESOURCES)
        .filter((f) => !f.startsWith('.') && IMAGE_EXT.has(extname(f).toLowerCase()))
        .sort()
    : [];

  const referenced = new Map();
  for (const s of db.styles) if (s.image) referenced.set(basename(s.image), s);

  const takenIds = new Set(db.styles.map((s) => s.id));
  const added = [];

  for (const file of files) {
    if (referenced.has(file)) {
      delete referenced.get(file).missing;
      continue;
    }
    let id = slug(basename(file, extname(file)));
    while (takenIds.has(id)) id = `${id}-2`;
    takenIds.add(id);

    const draft = {
      id,
      title: `Untitled — ${file}`,
      category: 'unsorted',
      image: `resources/${file}`,
      draft: true,
      short: 'Not classified yet. Run the classify prompt in README.md to fill this in.',
      long: 'This screenshot was found in /resources but has not been analysed yet. Ask Claude to classify the drafts and it will write the title, description, keywords, palette, traits and image prompt for you.',
      keywords: ['unclassified'],
      palette: ['#d9d9d9', '#a3a3a3', '#6b6b6b', '#2b2b2b'],
      traits: {},
      prompt: '',
    };
    db.styles.push(draft);
    added.push(file);
  }

  const missing = [];
  for (const [file, style] of referenced) {
    if (!files.includes(file)) {
      style.missing = true;
      missing.push(`${file} (${style.id})`);
    }
  }

  writeFileSync(JSON_PATH, JSON.stringify(db, null, 2) + '\n');

  const payload = { generatedAt: new Date().toISOString(), ...db };
  writeFileSync(
    JS_PATH,
    '/* GENERATED by scripts/sync.mjs — do not edit. Edit data/styles.json instead. */\n' +
      'window.DESIGN_LIBRARY = ' +
      JSON.stringify(payload, null, 2) +
      ';\n'
  );

  const drafts = db.styles.filter((s) => s.draft).length;
  if (!quiet) {
    console.log(`resources : ${files.length} image(s)`);
    console.log(`styles    : ${db.styles.length} entr(ies), ${drafts} draft(s)`);
    if (added.length) {
      console.log(`\nnew (added as drafts):`);
      for (const f of added) console.log(`  + ${f}`);
      console.log(`\nAsk Claude Code:  "classify the drafts in data/styles.json"`);
    }
    if (missing.length) {
      console.log(`\nmissing images (entries kept, flagged):`);
      for (const m of missing) console.log(`  ! ${m}`);
    }
    if (!added.length && !missing.length) console.log('\nup to date.');
  }

  return { files: files.length, added, missing, drafts };
}

if (import.meta.url === `file://${process.argv[1]}`) sync();
